version: '3.5'
services:
  jupyter:
    image: jupyter/base-notebook
    container_name: groupJupyter
    hostname: groupJupyter
    restart: unless-stopped
    user: root
    ports:
      - '8889:8888'
    volumes:
      - ./volumes/jupyter:/home/jovyan/
  api:
    build: 
      context: .
      dockerfile: api/Dockerfile
    ports:
      - '1111:80'
    restart: unless-stopped
    container_name: groupApi
    hostname: groupApi
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - '80:80'
    restart: unless-stopped
    container_name: groupWeb
    hostname: groupWeb