version: '3'
services:
  jupyter:
    image: jupyter/base-notebook
    container_name: groupJupyter
    hostname: groupJupyter
    restart: unless-stopped
    user: root
    ports:
      - '8889:8889'
    volumes:
      - ./volumes/jupyter:/home/jovyan/